### ISSUE TITLE
hill, when i run command `virtualenv venv`, it show errors like what i write blew

### ISSUE THREAD

**Issue by Gwan-Wang** [xpleaf/Blog_mini#2]
New python executable in /var/www/html/Blog_mini/venv/bin/python
Installing setuptools, pip, wheel...
  Complete output from command /var/www/html/Blog_mini/venv/bin/python - setuptools pip wheel:
  Traceback (most recent call last):
  File "<stdin>", line 23, in <module>
  File "/usr/lib/python2.6/site-packages/virtualenv-15.0.1-py2.6.egg/virtualenv_support/pip-8.1.1-py2.py3-none-any.whl/pip/__init__.py", line 215, in main
  File "/var/www/html/Blog_mini/venv/lib64/python2.6/locale.py", line 513, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
----------------------------------------
...Installing setuptools, pip, wheel...done.
Traceback (most recent call last):
  File "/usr/bin/virtualenv", line 9, in <module>
    load_entry_point('virtualenv==15.0.1', 'console_scripts', 'virtualenv')()
  File "/usr/lib/python2.6/site-packages/virtualenv-15.0.1-py2.6.egg/virtualenv.py", line 708, in main
    symlink=options.symlink)
  File "/usr/lib/python2.6/site-packages/virtualenv-15.0.1-py2.6.egg/virtualenv.py", line 941, in create_environment
    download=download,
  File "/usr/lib/python2.6/site-packages/virtualenv-15.0.1-py2.6.egg/virtualenv.py", line 897, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "/usr/lib/python2.6/site-packages/virtualenv-15.0.1-py2.6.egg/virtualenv.py", line 792, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /var/www/html/Blog_mini/venv/bin/python - setuptools pip wheel failed with error code 1

PS: locale.Error: unsupported locale setting

**Comment by xpleaf** [comment]
Use this way:`virtualenv test --no-setuptools --no-pip --no-wheel`

**Comment by xpleaf** [comment]
may be this will word for you,  
`virtualenv --system-site-packages myenv`  
I found it here:https://bitbucket.org/pypa/setuptools/issues/129  
You can take a reference.

**Comment by imlonghao** [comment]
Thanks for your insteresting in this project.
Please check your locales configure in your system.

Check: https://stackoverflow.com/questions/14547631/python-locale-error-unsupported-locale-setting
