### ISSUE TITLE
Broken pipe

### ISSUE THREAD

**Issue by Sakakibara-Hu** [xpleaf/Blog_mini#21]
有时会报这个错误，有时又不会，但是对网站访问好像又没什么影响，想问一下是和gunicorn有关的什么吗？
```
[2018-05-10 22:56:02 +0000] [29972] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/sakakibara/project/Blog_mini/venv/local/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 174, in handle_request
    resp.write_file(respiter)
  File "/home/sakakibara/project/Blog_mini/venv/local/lib/python2.7/site-packages/gunicorn/http/wsgi.py", line 397, in write_file
    if not self.sendfile(respiter):
  File "/home/sakakibara/project/Blog_mini/venv/local/lib/python2.7/site-packages/gunicorn/http/wsgi.py", line 387, in sendfile
    sent += sendfile(sockno, fileno, offset + sent, count)
  File "/home/sakakibara/project/Blog_mini/venv/local/lib/python2.7/site-packages/gunicorn/http/_sendfile.py", line 67, in sendfile
    raise OSError(e, os.strerror(e))
OSError: [Errno 32] Broken pipe

```

**Comment by xpleaf** [comment]
这个确实不影响，gunicorn的问题，有时就是这样，我也遇到过，你的PR我有空再看一下，最近事情比较多

**Comment by Sakakibara-Hu** [comment]
恩，好的。然后我看到有个issue说验证码 #10 大概做了一个简单的回复评论验证码，测试可用，也发过来你看下
