### ISSUE TITLE
Update for python3. https://github.com/huangtao36/Blog_mini

### ISSUE THREAD

**Issue by huangtao36** [xpleaf/Blog_mini#49]
all done. [https://github.com/huangtao36/Blog_mini](https://github.com/huangtao36/Blog_mini)

**Comment by zhangguolin333** [comment]
@huangtao36  python manage.py deploy product  报异常 
daniao@ubuntu:~/project/Blog_mini$ python3 manage.py deploy product
Traceback (most recent call last):
  File "manage.py", line 9, in <module>
    app = create_app()
  File "/home/daniao/project/Blog_mini/app/__init__.py", line 19, in create_app
    app = Flask(__name__)
  File "/home/daniao/.local/lib/python3.8/site-packages/flask/app.py", line 601, in __init__
    self.add_url_rule(
  File "/home/daniao/.local/lib/python3.8/site-packages/flask/app.py", line 98, in wrapper_func
    return f(self, *args, **kwargs)
  File "/home/daniao/.local/lib/python3.8/site-packages/flask/app.py", line 1278, in add_url_rule
    self.url_map.add(rule)
  File "/home/daniao/.local/lib/python3.8/site-packages/werkzeug/routing.py", line 1563, in add
    rule.bind(self)
  File "/home/daniao/.local/lib/python3.8/site-packages/werkzeug/routing.py", line 710, in bind
    self.compile()
  File "/home/daniao/.local/lib/python3.8/site-packages/werkzeug/routing.py", line 766, in compile
    self._build = self._compile_builder(False)
  File "/home/daniao/.local/lib/python3.8/site-packages/werkzeug/routing.py", line 1129, in _compile_builder
    return self.BuilderCompiler(self).compile(append_unknown)
  File "/home/daniao/.local/lib/python3.8/site-packages/werkzeug/routing.py", line 1120, in compile
    co = types.CodeType(*code_args)
TypeError: code() takes at least 14 arguments (13 given)
